//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_patient_ext
    {
        public System.Guid patient_id { get; set; }
        public string attribute_name { get; set; }
        public string attribute_value { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual hmis_patient_base hmis_patient_base { get; set; }
    }
}
