//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_decease_type_master
    {
        public System.Guid ID { get; set; }
        public string decease_type_name { get; set; }
        public string description { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime modified_on { get; set; }
        public System.Guid created_by { get; set; }
        public System.Guid modified_by { get; set; }
        public bool status { get; set; }
    
        public virtual hmis_user_base hmis_user_base { get; set; }
        public virtual hmis_user_base hmis_user_base1 { get; set; }
    }
}
