//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_patient_base
    {
        public System.Guid ID { get; set; }
        public string patient_registration_no { get; set; }
        public string patient_first_name { get; set; }
        public string patient_last_name { get; set; }
        public Nullable<System.DateTime> patient_dob { get; set; }
        public string patient_sex { get; set; }
        public string patient_blood_type { get; set; }
        public string patient_phone { get; set; }
        public string patient_notes { get; set; }
        public string patient_address { get; set; }
        public string patient_city { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime modified_on { get; set; }
        public System.Guid created_by { get; set; }
        public System.Guid modified_by { get; set; }
        public string additiona_info { get; set; }
    
        public virtual hmis_user_base hmis_user_base { get; set; }
        public virtual hmis_user_base hmis_user_base1 { get; set; }
        public virtual hmis_patient_ext hmis_patient_ext { get; set; }
    }
}
