//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_user_activity_log
    {
        public Nullable<System.Guid> user_id { get; set; }
        public string Outcome { get; set; }
        public string Actions { get; set; }
        public System.DateTime created_on { get; set; }
        public string message { get; set; }
    }
}
