//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_patient_operation
    {
        public System.Guid ID { get; set; }
        public System.Guid patient_admission_id { get; set; }
        public Nullable<System.DateTime> date_of_operation { get; set; }
        public Nullable<int> number_of_nights { get; set; }
        public string proposed_surgery { get; set; }
        public Nullable<bool> consent_on_surgery { get; set; }
        public Nullable<bool> consent_on_admission { get; set; }
        public string notes_on_surgery { get; set; }
        public string consignee_name { get; set; }
        public string consignee_relationship { get; set; }
        public string special_instruction { get; set; }
        public string medical_notes { get; set; }
        public int index_nember { get; set; }
        public System.Guid modified_by { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime modified_on { get; set; }
        public string operation_sequence { get; set; }
    
        public virtual hmis_patient_admission_base hmis_patient_admission_base { get; set; }
        public virtual hmis_user_base hmis_user_base { get; set; }
        public virtual hmis_user_base hmis_user_base1 { get; set; }
    }
}
