//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmis_user_ext
    {
        public System.Guid SID { get; set; }
        public string attribute_name { get; set; }
    
        public virtual hmis_user_base hmis_user_base { get; set; }
    }
}
