using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessEntities
{
    public class hmisPatientAdmissionExt
    {
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated from a template.
        //
        //     Manual changes to this file may cause unexpected behavior in your application.
        //     Manual changes to this file will be overwritten if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        public System.Guid patient_admission_id { get; set; }
        public System.Guid ID { get; set; }
        public string attribute_name { get; set; }
        public string attribute_value { get; set; }

        public virtual hmisPatientAdmissionBase hmis_patient_admission_base { get; set; }
    }
}
