//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_roles
    {
        public System.Guid user_id { get; set; }
        public string role_name { get; set; }
        public bool is_active { get; set; }
        public string role_description { get; set; }
    }
}
